language: android
os: linux
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - build-tools-29.0.2
  - android-29
  licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script:
- echo "$SIGNING_KEY" | base64 --decode > keystore.jks
- echo "storeFile=${CURPWD}/keystore.jks" > android/key.properties
- echo "storePassword=$KEY_STORE_PASSWORD" >> android/key.properties
- echo "keyAlias=$ALIAS" >> android/key.properties
- echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
script:
- ./gradlew assembleProd
- git clone https://github.com/apptestai/ci_addon
- export binary_path="app/build/outputs/apk/prod/release/app-prod-release.apk"
- export project_id='1111'
- export time_limit='5'
- bash ./ci_addon/step.sh
