language: android
os: linux
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - build-tools-29.0.2
  - android-29
  licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script:
- mkdir -p $HOME/.sign/
- CURPWD=$(pwd)
- echo "$SIGNING_KEY" | base64 --decode > keystore.jks
- echo "" > ~/.sign/signing.properties
- echo "keystore=${CURPWD}/keystore.jks" >> ~/.sign/signing.properties
- echo "store.pass=$KEY_STORE_PASSWORD" >> ~/.sign/signing.properties
- echo "key.alias=$ALIAS" >> ~/.sign/signing.properties
- echo "key.pass=$KEY_PASSWORD" >> ~/.sign/signing.properties
script:
- ./gradlew assembleProd
- git clone https://github.com/apptestai/ci_addon
- export binary_path="app/build/outputs/apk/prod/release/app-prod-release.apk"
- export project_id='1111'
- export time_limit='5'
- bash ./ci_addon/step.sh
